# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx.builder common options: html (default), dirhtml, singlehtml
# see https://www.sphinx-doc.org/en/master/man/sphinx-build.html for details
sphinx:
   builder: dirhtml
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF; options: htmlzip, pdf, epub, all (build all formats)
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
# (Configuration of the Python environment to be used.)
python:
   version: 3.8
   install:
   - requirements: docs/requirements.txt

# Configuration for Conda support
conda:
  environment: docs/environment.yaml
