# File: docs/environment.yaml
# This is the configuration file for Conda environment (see .readthedocs.yaml for details)
# Defining the exact version will make sure things don't break
name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==3.4.3
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.1
