# File: FE2D_DomainDecop/docs/environment.yaml
# This is the configuration file for Conda environment (see FE2D_DomainDecop/.readthedocs.yaml for details)
# Defining the exact version will make sure things don't break
name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.1.2
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.1
